#!/usr/bin/env bash

BATTERY_PATH="/sys/class/power_supply/BAT0"

LOW_THRES=19
HIGH_THRES=95

low_notified=false
high_notified=false

while true; do
    if [ -d "$BATTERY_PATH" ]; then
        CAPACITY=$(cat "$BATTERY_PATH/capacity")
        STATUS=$(cat "$BATTERY_PATH/status")

        if [ "$CAPACITY" -le "$LOW_THRES" ] && [ "$STATUS" = "Discharging" ]; then
            if [ "$low_notified" = false ]; then
                notify-send -u critical -a "Battery Monitor" -c "battery-alert" \
                    "󰂃 Low Battery" "Battery is down to ${CAPACITY}%!"
                low_notified=true
            fi
        elif [ "$CAPACITY" -gt "$LOW_THRES" ]; then
            low_notified=false
        fi

        if [ "$CAPACITY" -ge "$HIGH_THRES" ] && [ "$STATUS" = "Charging" ]; then
            if [ "$high_notified" = false ]; then
                notify-send -u critical -a "Battery Monitor" -c "battery-alert" \
                    "󰂅 Battery Charged" "Battery reached ${CAPACITY}%!"
                high_notified=true
            fi
        elif [ "$CAPACITY" -lt "$HIGH_THRES" ]; then
            high_notified=false
        fi
    fi
    sleep 5
done
